name: de_pv_data

services:

  postgres18:
    image: postgres:18
    container_name: postgres18
    environment:
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
    volumes:
      - vol_postgres_data:/var/lib/postgresql/18/docker
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 1G
        reservations:
          cpus: 1.0
          memory: 256MB

  python-scrap-pv:
    image: python:3.12.10
    working_dir: /app
    volumes:
      - .:/app/

    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python pv_web_scrap.py"

  python-get-meteo:
    image: python:3.12.10
    working_dir: /app
    volumes:
      - .:/app/

    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python meteo_get.py"

  python-insert-pv:
    image: python:3.12.10
    working_dir: /app
    volumes:
      - .:/app/
    links:
      - postgres18
    depends_on:
      postgres18:
        condition: service_started
      python-scrap-pv:
        condition: service_completed_successfully
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python pv_into_postgres.py"

  python-insert-meteo:
    image: python:3.12.10
    working_dir: /app
    volumes:
      - .:/app/
    links:
      - postgres18
    depends_on:
      postgres18:
        condition: service_started
      python-get-meteo:
        condition: service_completed_successfully
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python meteo_into_postgres.py"

  python-bronze-silver:
    image: python:3.12.10
    working_dir: /app
    volumes:
      - .:/app/
    links:
      - postgres18
    depends_on:
      postgres18:
        condition: service_started
      python-insert-meteo:
        condition: service_completed_successfully
      python-insert-pv:
        condition: service_completed_successfully
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python meteo_into_postgres.py"

volumes:
  vol_postgres_data:
    name: vol_postgres_data
    driver: local
